name: Cancel

on:
  repository_dispatch:
    types: [cancel-command]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: run
        run: echo Hello it canceled  
